# Generated by Django 4.1.2 on 2022-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departurecountry',
            name='have_risk',
            field=models.BooleanField(null=True),
        ),
    ]
