# Generated by Django 4.1.2 on 2022-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_departurecountry_have_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departurecountry',
            name='have_risk',
            field=models.BooleanField(default=False),
        ),
    ]
