# Generated by Django 4.1.2 on 2022-11-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_operation_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='netto',
            field=models.FloatField(verbose_name='Вес'),
        ),
    ]
